name: Build and Release

on:
  push:
    paths:
      - 'ulc/src/**'
  pull_request:
    paths:
      - 'ulc/src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd ulc/src
          npm install

      - name: Build project
        run: |
          cd ulc/src
          npm run build

      - name: Zip ulc folder for release
        run: |
          zip -r ulc-release.zip ulc

      - name: Upload release zip as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ulc-release
          path: ulc-release.zip
